export default [
    {   
        id: 1,
        img: require('../../img/cards/card_1.png'),
        rating: '5.0',
        rewiewCount: '(3)',
        country: 'Ukrain',
        title: 'Life lessons with Katie Zaferes',
        price: '135',
        openSpots: 0,
        location: "Online",
    },
    {
        id: 2,
        img: require('../../img/cards/card_2.png'),
        rating: '3.5',
        rewiewCount: '(6)',
        country: 'USA',
        title: 'Life lessons with Katie Zaferes',
        price: '452',
        openSpots: 27,
        location: "Online",
    },
    {
        id: 3,
        img: require('../../img/cards/card_2.png'),
        rating: '3.5',
        rewiewCount: '(6)',
        country: 'USA',
        title: 'Life lessons with Katie Zaferes',
        price: '452',
        openSpots: 3,
        location: "Online",
    },
    {
        id: 4,
        img: require('../../img/cards/card_2.png'),
        rating: '3.5',
        rewiewCount: '(6)',
        country: 'USA',
        title: 'Life lessons with Katie Zaferes',
        price: '452',
        openSpots: 0,
        location: "Online",
    },
    {
        id: 5,
        img: require('../../img/cards/card_2.png'),
        rating: '3.5',
        rewiewCount: '(6)',
        country: 'USA',
        title: 'Life lessons with Katie Zaferes',
        price: '452',
        openSpots: 137,
        location: "Online",
    },
    
]